#include "iq/CodeGen/CodeGen.h"

#include "iq/AST/Casting.h"
#include "iq/Diag/Diagnostic.h"
#include "iq/Sema/Sym.h"
#include "iq/Source/SourceManager.h"
#include "iq/Support/StringInterner.h"

#include <format>

namespace iq
{

namespace
{

bool isSignedKind(Type::Kind k)
{
    return k == Type::Kind::I32 || k == Type::Kind::I64;
}

int intBits(Type::Kind k)
{
    switch (k)
    {
    case Type::Kind::I32:
    case Type::Kind::U32: return 32;
    case Type::Kind::I64:
    case Type::Kind::U64: return 64;
    default:              return 0;
    }
}

} // namespace

CodeGen::CodeGen(
    SourceManager const& sm,
    StringInterner const& interner,
    DiagnosticEngine& diags,
    TypeContext& types
)
    : m_sm(sm), m_interner(interner), m_diags(diags), m_types(types)
{
}

void CodeGen::unsupported(SourceSpan span, std::string_view what)
{
    m_diags.error(span, std::format("code generation does not support {} yet", what));
}

std::string CodeGen::llvmType(Type const* t)
{
    if (!t)
    {
        return "i32";
    }
    switch (t->kind)
    {
    case Type::Kind::I32:
    case Type::Kind::U32: return "i32";
    case Type::Kind::I64:
    case Type::Kind::U64: return "i64";
    case Type::Kind::F32: return "float";
    case Type::Kind::F64: return "double";
    case Type::Kind::Bool: return "i1";
    case Type::Kind::Void: return "void";
    case Type::Kind::String: return "ptr";
    case Type::Kind::UntypedInt: return "i32";
    case Type::Kind::UntypedFloat: return "double";
    default: return "i32";
    }
}

// ---------------------------------------------------------------------------
// IR-building helpers
// ---------------------------------------------------------------------------

std::string CodeGen::freshTemp()
{
    return std::format("%t{}", m_temp++);
}

std::string CodeGen::freshLabel(std::string_view hint)
{
    return std::format("{}{}", hint, m_label++);
}

void CodeGen::label(std::string const& name)
{
    m_body += std::format("{}:\n", name);
    m_terminated = false;
}

void CodeGen::line(std::string const& text)
{
    if (m_terminated)
    {
        return;     // unreachable; drop
    }
    m_body += std::format("  {}\n", text);
}

void CodeGen::terminate(std::string const& text)
{
    if (m_terminated)
    {
        return;
    }
    m_body += std::format("  {}\n", text);
    m_terminated = true;
}

void CodeGen::br(std::string const& target)
{
    terminate(std::format("br label %{}", target));
}

void CodeGen::condBr(
    std::string const& cond,
    std::string const& ifTrue,
    std::string const& ifFalse
)
{
    terminate(std::format("br i1 {}, label %{}, label %{}", cond, ifTrue, ifFalse));
}

std::string CodeGen::allocaFor(Sym const* sym)
{
    if (auto it = m_locals.find(sym); it != m_locals.end())
    {
        return it->second;
    }
    std::string slot = std::format("%{}.{}", m_interner.lookup(sym->name), m_temp++);
    m_entry += std::format("  {} = alloca {}\n", slot, llvmType(sym->type));
    m_locals.emplace(sym, slot);
    return slot;
}

std::string CodeGen::addrOf(Sym const* sym) const
{
    if (auto it = m_locals.find(sym); it != m_locals.end())
    {
        return it->second;
    }
    if (auto it = m_globals.find(sym); it != m_globals.end())
    {
        return it->second;
    }
    return "%bad.addr";
}

std::string CodeGen::numericLiteral(NumberLiteral const* lit) const
{
    std::string_view text = m_sm.spanText(lit->span);
    std::size_t end = 0;
    while (end < text.size()
        && ((text[end] >= '0' && text[end] <= '9') || text[end] == '.'))
    {
        ++end;
    }
    return std::string(text.substr(0, end));
}

std::string CodeGen::internCString(std::string_view bytes)
{
    std::string escaped;
    std::size_t len = 0;
    for (char const c : bytes)
    {
        unsigned char const u = static_cast<unsigned char>(c);
        if (u >= 0x20 && u < 0x7f && u != '"' && u != '\\')
        {
            escaped += c;
        }
        else
        {
            escaped += std::format("\\{:02X}", u);
        }
        ++len;
    }
    escaped += "\\00";
    ++len;

    std::string name = std::format("@.str.{}", m_str++);
    m_header += std::format(
        "{} = private unnamed_addr constant [{} x i8] c\"{}\"\n", name, len, escaped);
    return name;
}

// ---------------------------------------------------------------------------
// Module
// ---------------------------------------------------------------------------

std::string CodeGen::run(Module const& module)
{
    m_header += "; LLVM IR generated by the IQ-- compiler\n\n";
    m_header += "declare i32 @printf(ptr, ...)\n\n";

    // printf format strings (newline-terminated, like the language's print).
    m_header += "@.fmt.i32 = private unnamed_addr constant [4 x i8] c\"%d\\0A\\00\"\n";
    m_header += "@.fmt.u32 = private unnamed_addr constant [4 x i8] c\"%u\\0A\\00\"\n";
    m_header += "@.fmt.i64 = private unnamed_addr constant [6 x i8] c\"%lld\\0A\\00\"\n";
    m_header += "@.fmt.u64 = private unnamed_addr constant [6 x i8] c\"%llu\\0A\\00\"\n";
    m_header += "@.fmt.f64 = private unnamed_addr constant [4 x i8] c\"%f\\0A\\00\"\n";
    m_header += "@.fmt.str = private unnamed_addr constant [4 x i8] c\"%s\\0A\\00\"\n\n";

    for (Decl const* decl : module.decls)
    {
        if (auto const* c = dyn_cast<ConstDecl>(decl))
        {
            emitConstGlobal(c);
        }
    }

    for (Decl const* decl : module.decls)
    {
        if (auto const* fn = dyn_cast<FnDecl>(decl))
        {
            emitFn(fn);
        }
    }

    return m_header + "\n" + m_funcs;
}

void CodeGen::emitConstGlobal(ConstDecl const* c)
{
    if (!c->sym)
    {
        return;
    }
    std::string name = std::format("@{}", m_interner.lookup(c->sym->name));
    std::string ty = llvmType(c->sym->type);

    std::string value = "0";
    if (auto const* lit = dyn_cast<NumberLiteral>(c->init))
    {
        value = numericLiteral(lit);
    }
    else if (auto const* b = dyn_cast<BoolLiteral>(c->init))
    {
        value = b->value ? "1" : "0";
    }
    else
    {
        unsupported(c->span, "a const initialized by a non-literal");
    }

    m_header += std::format("{} = constant {} {}\n", name, ty, value);
    m_globals.emplace(c->sym, name);
}

std::string CodeGen::llvmReturnType(FnDecl const* fn)
{
    if (!fn->returnType)
    {
        return "void";
    }
    if (auto const* named = dyn_cast<NamedType>(fn->returnType))
    {
        std::string_view const n = m_interner.lookup(named->name);
        if (n == "i32" || n == "u32") { return "i32"; }
        if (n == "i64" || n == "u64") { return "i64"; }
        if (n == "f32")    { return "float"; }
        if (n == "f64")    { return "double"; }
        if (n == "bool")   { return "i1"; }
        if (n == "string") { return "ptr"; }
        if (n == "void")   { return "void"; }
    }
    unsupported(fn->returnType->span, "this return type");
    return "i32";
}

void CodeGen::emitFn(FnDecl const* fn)
{
    m_entry.clear();
    m_body.clear();
    m_locals.clear();
    m_loops.clear();
    m_temp = 0;
    m_label = 0;
    m_terminated = false;

    std::string const fnName = std::string(m_interner.lookup(fn->name));
    m_inMain = (fnName == "main");

    // main is lowered to `i32 @main` regardless of its void source signature.
    std::string retIr = m_inMain ? "i32" : llvmReturnType(fn);

    // Build parameter list and stash incoming values into entry-block slots.
    std::string params;
    for (std::size_t i = 0; i < fn->params.size(); ++i)
    {
        Param const& p = fn->params[i];
        std::string pty = llvmType(p.sym ? p.sym->type : nullptr);
        std::string incoming = std::format("%{}", m_interner.lookup(p.name));
        if (i != 0)
        {
            params += ", ";
        }
        params += std::format("{} {}", pty, incoming);

        std::string slot = allocaFor(p.sym);
        m_entry += std::format("  store {} {}, ptr {}\n", pty, incoming, slot);
    }

    emitBlock(fn->body);

    if (!m_terminated)
    {
        if (m_inMain)
        {
            terminate("ret i32 0");
        }
        else if (retIr == "void")
        {
            terminate("ret void");
        }
        else
        {
            terminate("unreachable");
        }
    }

    m_funcs += std::format("define {} @{}({}) {{\n", retIr, fnName, params);
    m_funcs += "entry:\n";
    m_funcs += m_entry;
    m_funcs += m_body;
    m_funcs += "}\n\n";
}

// ---------------------------------------------------------------------------
// Statements
// ---------------------------------------------------------------------------

void CodeGen::emitBlock(BlockStmt const* block)
{
    for (Stmt const* s : block->statements)
    {
        emitStmt(s);
    }
}

void CodeGen::emitStmt(Stmt const* stmt)
{
    switch (stmt->kind)
    {
    case StmtKind::Block:
        emitBlock(cast<BlockStmt>(stmt));
        return;

    case StmtKind::Let:
    {
        auto const* let = cast<LetStmt>(stmt);
        auto const* ident = dyn_cast<IdentPattern>(let->pattern);
        if (!ident)
        {
            unsupported(let->span, "destructuring patterns");
            return;
        }
        std::string slot = allocaFor(ident->sym);
        if (let->init)
        {
            std::string v = emitExpr(let->init);
            line(std::format("store {} {}, ptr {}",
                             llvmType(ident->sym->type), v, slot));
        }
        return;
    }

    case StmtKind::Expr:
        emitExpr(cast<ExprStmt>(stmt)->expr);
        return;

    case StmtKind::Return:
    {
        auto const* ret = cast<ReturnStmt>(stmt);
        if (m_inMain)
        {
            terminate("ret i32 0");
        }
        else if (ret->value)
        {
            std::string v = emitExpr(ret->value);
            terminate(std::format("ret {} {}", llvmType(ret->value->type), v));
        }
        else
        {
            terminate("ret void");
        }
        return;
    }

    case StmtKind::Break:
        if (!m_loops.empty())
        {
            br(m_loops.back().breakTarget);
        }
        return;

    case StmtKind::Continue:
        if (!m_loops.empty())
        {
            br(m_loops.back().continueTarget);
        }
        return;

    case StmtKind::If:
    {
        auto const* node = cast<IfStmt>(stmt);
        std::string cond = emitExpr(node->cond);
        std::string thenL = freshLabel("then");
        std::string endL = freshLabel("endif");

        if (node->elseBranch)
        {
            std::string elseL = freshLabel("else");
            condBr(cond, thenL, elseL);

            label(thenL);
            emitStmt(node->thenBranch);
            bool const thenTerm = m_terminated;
            br(endL);

            label(elseL);
            emitStmt(node->elseBranch);
            bool const elseTerm = m_terminated;
            br(endL);

            if (thenTerm && elseTerm)
            {
                m_terminated = true;    // both arms diverged; endL is unreachable
            }
            else
            {
                label(endL);
            }
        }
        else
        {
            condBr(cond, thenL, endL);
            label(thenL);
            emitStmt(node->thenBranch);
            br(endL);
            label(endL);
        }
        return;
    }

    case StmtKind::While:
    {
        auto const* node = cast<WhileStmt>(stmt);
        std::string condL = freshLabel("while.cond");
        std::string bodyL = freshLabel("while.body");
        std::string endL = freshLabel("while.end");

        br(condL);
        label(condL);
        std::string cond = emitExpr(node->cond);
        condBr(cond, bodyL, endL);

        m_loops.push_back({ condL, endL });
        label(bodyL);
        emitStmt(node->body);
        br(condL);
        m_loops.pop_back();

        label(endL);
        return;
    }

    case StmtKind::For:
    {
        auto const* node = cast<ForStmt>(stmt);
        auto const* range = dyn_cast<RangeExpr>(node->iter);
        auto const* ident = dyn_cast<IdentPattern>(node->var);
        if (!range || !ident)
        {
            unsupported(node->span, "this kind of for loop");
            return;
        }

        Type const* elemType = ident->sym->type;
        std::string ty = llvmType(elemType);
        bool const signedCmp = isSignedKind(elemType->kind);
        std::string const ltPred = range->inclusive
            ? (signedCmp ? "sle" : "ule")
            : (signedCmp ? "slt" : "ult");

        std::string slot = allocaFor(ident->sym);
        std::string lo = emitExpr(range->lo);
        std::string hi = emitExpr(range->hi);
        line(std::format("store {} {}, ptr {}", ty, lo, slot));

        std::string condL = freshLabel("for.cond");
        std::string bodyL = freshLabel("for.body");
        std::string incL = freshLabel("for.inc");
        std::string endL = freshLabel("for.end");

        br(condL);
        label(condL);
        std::string cur = freshTemp();
        line(std::format("{} = load {}, ptr {}", cur, ty, slot));
        std::string cmp = freshTemp();
        line(std::format("{} = icmp {} {} {}, {}", cmp, ltPred, ty, cur, hi));
        condBr(cmp, bodyL, endL);

        m_loops.push_back({ incL, endL });
        label(bodyL);
        emitStmt(node->body);
        br(incL);
        m_loops.pop_back();

        label(incL);
        std::string iv = freshTemp();
        line(std::format("{} = load {}, ptr {}", iv, ty, slot));
        std::string next = freshTemp();
        line(std::format("{} = add {} {}, 1", next, ty, iv));
        line(std::format("store {} {}, ptr {}", ty, next, slot));
        br(condL);

        label(endL);
        return;
    }
    }
}

// ---------------------------------------------------------------------------
// Expressions
// ---------------------------------------------------------------------------

std::string CodeGen::emitExpr(Expr const* expr)
{
    switch (expr->kind)
    {
    case ExprKind::NumberLiteral:
        return numericLiteral(cast<NumberLiteral>(expr));

    case ExprKind::BoolLiteral:
        return cast<BoolLiteral>(expr)->value ? "true" : "false";

    case ExprKind::StringLiteral:
        return internCString(m_interner.lookup(cast<StringLiteral>(expr)->value));

    case ExprKind::Name:
    {
        auto const* name = cast<NameExpr>(expr);
        std::string ty = llvmType(name->type);
        std::string addr = addrOf(name->sym);
        std::string t = freshTemp();
        line(std::format("{} = load {}, ptr {}", t, ty, addr));
        return t;
    }

    case ExprKind::Unary:
    {
        auto const* un = cast<UnaryExpr>(expr);
        std::string v = emitExpr(un->operand);
        std::string ty = llvmType(un->type);
        std::string t = freshTemp();
        if (un->op == UnaryOp::Not)
        {
            line(std::format("{} = xor i1 {}, true", t, v));
        }
        else if (isFloat(un->type))
        {
            line(std::format("{} = fneg {} {}", t, ty, v));
        }
        else
        {
            line(std::format("{} = sub {} 0, {}", t, ty, v));
        }
        return t;
    }

    case ExprKind::Binary:
        return emitBinary(cast<BinaryExpr>(expr));

    case ExprKind::Assign:
    {
        auto const* assign = cast<AssignExpr>(expr);
        auto const* target = dyn_cast<NameExpr>(assign->target);
        if (!target)
        {
            unsupported(assign->span, "assignment to this kind of target");
            return "0";
        }
        std::string ty = llvmType(target->type);
        std::string addr = addrOf(target->sym);
        std::string rhs = emitExpr(assign->value);

        if (assign->op == AssignOp::Assign)
        {
            line(std::format("store {} {}, ptr {}", ty, rhs, addr));
            return rhs;
        }

        std::string cur = freshTemp();
        line(std::format("{} = load {}, ptr {}", cur, ty, addr));
        std::string res = freshTemp();
        bool const flt = isFloat(target->type);
        std::string op;
        switch (assign->op)
        {
        case AssignOp::Add: op = flt ? "fadd" : "add"; break;
        case AssignOp::Sub: op = flt ? "fsub" : "sub"; break;
        case AssignOp::Mul: op = flt ? "fmul" : "mul"; break;
        case AssignOp::Div: op = flt ? "fdiv" : (isSignedKind(target->type->kind) ? "sdiv" : "udiv"); break;
        case AssignOp::Rem: op = flt ? "frem" : (isSignedKind(target->type->kind) ? "srem" : "urem"); break;
        case AssignOp::Assign: break;
        }
        line(std::format("{} = {} {} {}, {}", res, op, ty, cur, rhs));
        line(std::format("store {} {}, ptr {}", ty, res, addr));
        return res;
    }

    case ExprKind::Call:
        return emitCall(cast<CallExpr>(expr));

    case ExprKind::Cast:
        return emitCast(cast<CastExpr>(expr));

    case ExprKind::Index:
        unsupported(expr->span, "array indexing");
        return "0";
    case ExprKind::Array:
        unsupported(expr->span, "array literals");
        return "0";
    case ExprKind::Tuple:
        unsupported(expr->span, "tuples");
        return "0";
    case ExprKind::Range:
        unsupported(expr->span, "ranges outside a for loop");
        return "0";
    }
    return "0";
}

std::string CodeGen::emitBinary(BinaryExpr const* bin)
{
    if (bin->op == BinaryOp::And || bin->op == BinaryOp::Or)
    {
        return emitShortCircuit(bin);
    }

    std::string l = emitExpr(bin->lhs);
    std::string r = emitExpr(bin->rhs);
    Type const* opType = bin->lhs->type;        // both operands share a type
    std::string ty = llvmType(opType);
    bool const flt = isFloat(opType);
    bool const sgn = isInteger(opType) && isSignedKind(opType->kind);
    std::string t = freshTemp();

    switch (bin->op)
    {
    case BinaryOp::Add: line(std::format("{} = {} {} {}, {}", t, flt ? "fadd" : "add", ty, l, r)); break;
    case BinaryOp::Sub: line(std::format("{} = {} {} {}, {}", t, flt ? "fsub" : "sub", ty, l, r)); break;
    case BinaryOp::Mul: line(std::format("{} = {} {} {}, {}", t, flt ? "fmul" : "mul", ty, l, r)); break;
    case BinaryOp::Div: line(std::format("{} = {} {} {}, {}", t, flt ? "fdiv" : (sgn ? "sdiv" : "udiv"), ty, l, r)); break;
    case BinaryOp::Rem: line(std::format("{} = {} {} {}, {}", t, flt ? "frem" : (sgn ? "srem" : "urem"), ty, l, r)); break;

    case BinaryOp::Eq: line(std::format("{} = {} {} {} {}, {}", t, flt ? "fcmp" : "icmp", flt ? "oeq" : "eq", ty, l, r)); break;
    case BinaryOp::Ne: line(std::format("{} = {} {} {} {}, {}", t, flt ? "fcmp" : "icmp", flt ? "one" : "ne", ty, l, r)); break;
    case BinaryOp::Lt: line(std::format("{} = {} {} {} {}, {}", t, flt ? "fcmp" : "icmp", flt ? "olt" : (sgn ? "slt" : "ult"), ty, l, r)); break;
    case BinaryOp::Le: line(std::format("{} = {} {} {} {}, {}", t, flt ? "fcmp" : "icmp", flt ? "ole" : (sgn ? "sle" : "ule"), ty, l, r)); break;
    case BinaryOp::Gt: line(std::format("{} = {} {} {} {}, {}", t, flt ? "fcmp" : "icmp", flt ? "ogt" : (sgn ? "sgt" : "ugt"), ty, l, r)); break;
    case BinaryOp::Ge: line(std::format("{} = {} {} {} {}, {}", t, flt ? "fcmp" : "icmp", flt ? "oge" : (sgn ? "sge" : "uge"), ty, l, r)); break;

    case BinaryOp::And:
    case BinaryOp::Or:
        break;      // handled above
    }
    return t;
}

std::string CodeGen::emitShortCircuit(BinaryExpr const* bin)
{
    // a && b  ->  if a then b else false
    // a || b  ->  if a then true else b
    bool const isAnd = (bin->op == BinaryOp::And);
    std::string l = emitExpr(bin->lhs);
    std::string lhsBlock = freshLabel("sc.lhs");
    std::string rhsBlock = freshLabel("sc.rhs");
    std::string endBlock = freshLabel("sc.end");

    // Record the block we branch from for the phi.
    br(lhsBlock);
    label(lhsBlock);
    if (isAnd)
    {
        condBr(l, rhsBlock, endBlock);
    }
    else
    {
        condBr(l, endBlock, rhsBlock);
    }

    label(rhsBlock);
    std::string r = emitExpr(bin->rhs);
    std::string rhsEnd = freshLabel("sc.rhsend");
    br(rhsEnd);
    label(rhsEnd);
    br(endBlock);

    label(endBlock);
    std::string t = freshTemp();
    std::string shortVal = isAnd ? "false" : "true";
    line(std::format("{} = phi i1 [ {}, %{} ], [ {}, %{} ]",
                     t, shortVal, lhsBlock, r, rhsEnd));
    return t;
}

std::string CodeGen::emitCall(CallExpr const* call)
{
    auto const* callee = dyn_cast<NameExpr>(call->callee);
    Sym const* sym = callee ? callee->sym : nullptr;

    if (sym && sym->kind == SymKind::Builtin)
    {
        emitPrint(call);
        return "";
    }

    if (sym && sym->kind == SymKind::Function)
    {
        auto const* fn = cast<FnDecl>(sym->decl);
        std::string args;
        for (std::size_t i = 0; i < call->args.size(); ++i)
        {
            std::string v = emitExpr(call->args[i]);
            if (i != 0)
            {
                args += ", ";
            }
            args += std::format("{} {}", llvmType(call->args[i]->type), v);
        }

        std::string retIr = llvmType(call->type);
        std::string name = std::string(m_interner.lookup(callee->name));
        if (retIr == "void")
        {
            line(std::format("call void @{}({})", name, args));
            return "";
        }
        std::string t = freshTemp();
        line(std::format("{} = call {} @{}({})", t, retIr, name, args));
        return t;
    }

    return "0";
}

void CodeGen::emitPrint(CallExpr const* call)
{
    if (call->args.empty())
    {
        return;
    }
    Expr const* arg = call->args[0];
    Type const* t = arg->type;
    std::string v = emitExpr(arg);

    auto printf = [&](std::string_view fmt, std::string_view argTy, std::string_view value)
    {
        line(std::format("call i32 (ptr, ...) @printf(ptr {}, {} {})", fmt, argTy, value));
    };

    if (!t)
    {
        printf("@.fmt.i32", "i32", v);
        return;
    }
    switch (t->kind)
    {
    case Type::Kind::I32: case Type::Kind::UntypedInt:
        printf("@.fmt.i32", "i32", v); break;
    case Type::Kind::U32:
        printf("@.fmt.u32", "i32", v); break;
    case Type::Kind::I64:
        printf("@.fmt.i64", "i64", v); break;
    case Type::Kind::U64:
        printf("@.fmt.u64", "i64", v); break;
    case Type::Kind::F64: case Type::Kind::UntypedFloat:
        printf("@.fmt.f64", "double", v); break;
    case Type::Kind::F32:
    {
        std::string d = freshTemp();
        line(std::format("{} = fpext float {} to double", d, v));
        printf("@.fmt.f64", "double", d);
        break;
    }
    case Type::Kind::Bool:
    {
        std::string z = freshTemp();
        line(std::format("{} = zext i1 {} to i32", z, v));
        printf("@.fmt.i32", "i32", z);
        break;
    }
    case Type::Kind::String:
        printf("@.fmt.str", "ptr", v); break;
    default:
        unsupported(arg->span, "printing this type");
        break;
    }
}

std::string CodeGen::emitCast(CastExpr const* cst)
{
    std::string v = emitExpr(cst->value);
    Type const* from = cst->value->type;
    // CastExpr::type is the target TypeExpr annotation, which shadows the
    // inherited Expr::type; the resolved semantic type lives on the base.
    Type const* to = static_cast<Expr const*>(cst)->type;
    std::string fromTy = llvmType(from);
    std::string toTy = llvmType(to);

    if (!from || !to || from == to || fromTy == toTy)
    {
        return v;       // no-op (e.g. i32 -> u32 share an LLVM type)
    }

    std::string t = freshTemp();
    std::string op;

    bool const fromInt = isInteger(from) || isUntyped(from);
    bool const toInt = isInteger(to);
    bool const fromFlt = isFloat(from);
    bool const toFlt = isFloat(to);
    bool const fromSigned = from->kind == Type::Kind::I32 || from->kind == Type::Kind::I64
        || from->kind == Type::Kind::UntypedInt;

    if (fromInt && toInt)
    {
        int fb = from->kind == Type::Kind::UntypedInt ? 32 : intBits(from->kind);
        int tb = intBits(to->kind);
        op = tb > fb ? (fromSigned ? "sext" : "zext") : "trunc";
    }
    else if (fromInt && toFlt)
    {
        op = fromSigned ? "sitofp" : "uitofp";
    }
    else if (fromFlt && toInt)
    {
        op = (to->kind == Type::Kind::I32 || to->kind == Type::Kind::I64) ? "fptosi" : "fptoui";
    }
    else if (fromFlt && toFlt)
    {
        op = (toTy == "double") ? "fpext" : "fptrunc";
    }
    else
    {
        return v;
    }

    line(std::format("{} = {} {} {} to {}", t, op, fromTy, v, toTy));
    return t;
}

} // namespace iq